// --- Global State & Constants ---
// Sample product data, embedded to make the application runnable without a server.
let products = [
    {
        id: 'p001',
        name: 'Vintage Leather Bag',
        description: 'A stylish and durable vintage leather bag, perfect for everyday use. Features multiple compartments and a comfortable shoulder strap.',
        price: 120.00,
        imageUrl: 'https://www.anuent.com/cdn/shop/files/open-graph-image.jpg?v=1722356312',
        variants: [
            { color: 'Brown', sku: 'B001-BR' },
            { color: 'Black', sku: 'B001-BL' },
        ],
    },
    {
        id: 'p002',
        name: 'Wireless Bluetooth Headphones',
        description: 'Experience superior sound quality and ultimate comfort with these noise-cancelling wireless headphones. Up to 20 hours battery life.',
        price: 75.50,
        imageUrl: 'https://myshop.pk/pub/media/catalog/product/cache/26f8091d81cea4b38d820a1d1a4f62be/_/b/_beats-3_-myshop-pk-2.jpg',
        variants: [
            { color: 'Red', sku: 'H002-RD' },
            { color: 'Blue', sku: 'H002-BL' },
            { color: 'Black', sku: 'H002-BK' },
        ],
    },
    {
        id: 'p003',
        name: 'Smartwatch Pro X',
        description: 'Stay connected, track your fitness, and monitor your health with the sleek new Smartwatch Pro X. Waterproof and long-lasting battery.',
        price: 199.99,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3bmtmyHPpwb5Sw8Gp1wqDzoN1Ca8H7Fh6fw&s',
        variants: [
            { color: 'Silver', sku: 'SW003-SV' },
            { color: 'Gold', sku: 'SW003-GD' },
        ],
    },
    {
        id: 'p004',
        name: 'Portable Power Bank 10000mAh',
        description: 'Never run out of battery again with this high-capacity portable power bank. Fast charging and universal compatibility.',
        price: 35.00,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS73Hkjiyk9k4_EmqTfKncc7dIygPcxg8vvIA&s',
        variants: [],
    },
    {
        id: 'p005',
        name: 'Ergonomic Office Chair',
        description: 'Designed for maximum comfort and support during long working hours. Adjustable height, armrests, and lumbar support.',
        price: 280.00,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHkkqsZcauU3WTt1XDOzuRBeghtGehqy-eNQ&s',
        variants: [
            { color: 'Grey', sku: 'OC005-GY' },
            { color: 'Black', sku: 'OC005-BK' },
        ],
    },
    {
        id: 'p006',
        name: 'Bamboo Desk Organizer',
        description: 'Keep your workspace tidy with this eco-friendly and stylish bamboo desk organizer. Features multiple slots for pens, paper clips, and a small drawer for essentials.',
        price: 45.00,
        imageUrl: 'https://osco.com/wp-content/uploads/2023/08/BAM-ORG1-800x800.png',
        variants: [],
    },
    {
        id: 'p007',
        name: 'Ceramic Coffee Mug Set',
        description: 'A set of four handcrafted ceramic mugs, perfect for your morning coffee or evening tea. Available in a variety of earthy tones. Dishwasher and microwave safe.',
        price: 30.00,
        imageUrl: 'https://supa.pk/cdn/shop/files/61ic0nbS9LL._AC_SX679.jpg?v=1723474412',
        variants: [
            { color: 'Terracotta', sku: 'CM007-TC' },
            { color: 'Sage Green', sku: 'CM007-SG' },
            { color: 'Stone Grey', sku: 'CM007-ST' },
        ],
    },
    {
        id: 'p008',
        name: 'Stainless Steel Water Bottle',
        description: 'Stay hydrated on the go with this insulated stainless steel water bottle. Keeps drinks cold for up to 24 hours and hot for 12 hours. Leak-proof design.',
        price: 25.50,
        imageUrl: 'https://harshaystore.pk/cdn/shop/files/yMUQomqCu4jzs8jE_900x.png?v=1722685072',
        variants: [
            { color: 'Matte Black', sku: 'WB008-BK' },
            { color: 'Pearl White', sku: 'WB008-WH' },
            { color: 'Ocean Blue', sku: 'WB008-BL' },
        ],
    },
    {
        id: 'p009',
        name: 'Handmade Wool Blanket',
        description: 'Cozy up with this super soft and warm wool blanket, handwoven with care. A perfect addition to any living room or bedroom. Hypoallergenic and breathable.',
        price: 95.00,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6ZLQ7lAlOAFnP3C_tCRih3mGAAv8SrKHN-Q&s',
        variants: [
            { color: 'Charcoal Grey', sku: 'BL009-GY' },
            { color: 'Cream', sku: 'BL009-CR' },
        ],
    },
    {
        id: 'p010',
        name: 'Aromatherapy Diffuser',
        description: 'Create a calming atmosphere with this ultrasonic aromatherapy diffuser. Features an elegant wood grain finish and seven color-changing LED lights.',
        price: 50.00,
        imageUrl: 'https://static-01.daraz.pk/p/b8f274cde670aa36418a04027e523f8c.jpg',
        variants: [
            { color: 'Light Wood', sku: 'AD010-LW' },
            { color: 'Dark Wood', sku: 'AD010-DW' },
        ],
    },
    {
        id: 'p011',
        name: 'Minimalist Wall Clock',
        description: 'A sleek and modern wall clock with a silent, non-ticking movement. Its minimalist design fits perfectly in any contemporary space. Easy to hang and operate.',
        price: 65.00,
        imageUrl: 'https://thelovelydrawer.com/wp-content/uploads/2015/03/DIY-minimal-wall-clock-2.jpg',
        variants: [
            { color: 'Black Frame', sku: 'WC011-BK' },
            { color: 'Silver Frame', sku: 'WC011-SV' },
        ],
    },
    {
        id: 'p012',
        name: 'Yoga Mat with Carrying Strap',
        description: 'Enhance your practice with this non-slip, eco-friendly yoga mat. Provides excellent grip and cushioning for all types of yoga and fitness routines. Includes a convenient carrying strap.',
        price: 40.00,
        imageUrl: 'https://img.drz.lazcdn.com/static/pk/p/61435323e618249d583a0ebbc22a6a30.png_960x960q80.png_.webp',
        variants: [
            { color: 'Lilac', sku: 'YM012-LL' },
            { color: 'Navy Blue', sku: 'YM012-NB' },
            { color: 'Forest Green', sku: 'YM012-FG' },
        ],
    },
    {
        id: 'p013',
        name: 'Noise-Cancelling Earbuds',
        description: 'Immerse yourself in your music with these powerful noise-cancelling earbuds. Comes with a compact charging case and provides up to 30 hours of total playtime.',
        price: 89.99,
        imageUrl: 'https://vmart.pk/cdn/shop/files/Anker-Life-P3-Noise-Cancelling-Earbuds.webp?v=1737584527',
        variants: [
            { color: 'Black', sku: 'EB013-BK' },
            { color: 'White', sku: 'EB013-WH' },
        ],
    },
    {
        id: 'p014',
        name: 'Adjustable Laptop Stand',
        description: 'Improve your posture and reduce neck strain with this ergonomic adjustable laptop stand. Made from durable aluminum, it\'s foldable and lightweight for portability.',
        price: 55.00,
        imageUrl: 'https://img.drz.lazcdn.com/static/pk/p/238d90bcdc701209860c773c7359047b.jpg_720x720q80.jpg',
        variants: [],
    },
    {
        id: 'p015',
        name: 'Portable Espresso Maker',
        description: 'Enjoy a perfect shot of espresso anywhere with this compact and easy-to-use portable maker. No electricity needed, just a little hot water and your favorite ground coffee.',
        price: 70.00,
        imageUrl: 'https://staresso.com/cdn/shop/files/image-sp300-flair-portable-01-2-1440x1440.jpg?v=1741677429',
        variants: [],
    },
    {
        id: 'p016',
        name: 'Microfiber Cleaning Cloths (10-pack)',
        description: 'A set of ten ultra-absorbent and lint-free microfiber cloths. Perfect for cleaning glass, screens, and any other surface without streaks or scratches.',
        price: 15.00,
        imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBCC_5d7iDp-HvL5DcQKxN4nIUAnnqQBcsmw&s',
        variants: [
            { color: 'Blue', sku: 'CC016-BL' },
            { color: 'Yellow', sku: 'CC016-YE' },
            { color: 'Green', sku: 'CC016-GR' },
        ],
    },
];
